apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  type: LoadBalancer
  selector:
     app: microservice-api
  ports:
  - port: 8095
    targetPort: 8095
