apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: microservice-api
  template:
    metadata:
      labels:
        app: microservice-api
    spec:
      initContainers:
      - name: init-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z rds-mysql-external-service 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
      - name: microservice-api
        image: stacksimplify/kube-usermanagement-microservice:1.0.0
        env:
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: mysql-db-password
              key: db-host
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-password
              key: db-password
        - name: DB_NAME
          value: "usermgtdb"
        ports:
        - containerPort: 8095
        livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10     
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            cpu: "1000m"
            memory: "500Mi"