apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # This Annotation For Tell K8s to lb of type network traffic
spec:
  type: LoadBalancer
  selector:
     app: microservice-api
  ports:
  - port: 80
    targetPort: 8095
