apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data:
  db-password: ZGJwYXNzd29yZDEx
  db-host: YXVyb3JhLWNsdXN0ZXItZGVtby0wLmNnY255Y3Z3cTV4dS5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20=